# Site settings
title: Gig-n-Jam
email: info@gignjam.com
description: "This is the description of the site"
baseurl: ""
url: "http://www.gignjam.com" # the base hostname & protocol for your site
app: "http://app.gignjam.com"
# app: "http://localhost:3000"



facebook: https://www.facebook.com/gignjam
twitter: https://twitter.com/gignjam/
instagram: https://www.instagram.com/gignjam/
youtube: https://www.youtube.com/gignjam

# Build settings
markdown: kramdown


# Pictures
# Fans, entretain your guests, http://photodune.net/item/band-performs-on-stage/10033627?s_phrase=rock%20concert&s_rank=193

# home-festivals, http://photodune.net/item/audience-at-outdoor-music-festival/10850561?s_rank=6
# home-concerts, http://photodune.net/item/rock-concert/2409488?s_rank=26
# home-college-music, http://photodune.net/item/music-band-performing-on-a-stage/12467185?s_rank=3
# home-gigs, http://photodune.net/item/bass-guitar/9760599?s_rank=11
# home-indie, http://photodune.net/item/young-bearded-stylish-handsome-hipster-man-listening-music/7328885?s_rank=16
# home-pop, http://photodune.net/item/woman-rock-star/10796750?s_rank=214
# home-country, http://photodune.net/item/country-music-singer/2200190?s_rank=3
# home-alternative, http://photodune.net/item/music-mixer-and-digital-equalizer-at-concert-or-party-in-the-nightclub/14531812?s_rank=139