# Site settings
title: Gig-n-Jam
email: info@gignjam.com
description: "This is the description of the site"
baseurl: ""
url: "http://www.gignjam.com" # the base hostname & protocol for your site
# app: "http://app.gignjam.com"
app: "http://localhost:3000"


facebook: https://www.facebook.com/gignjam
twitter: https://twitter.com/gignjam/
instagram: https://www.instagram.com/gignjam/
youtube: https://www.youtube.com/gignjam

# Build settings
markdown: kramdown


# Pictures
# Fans, entretain your guests, http://photodune.net/item/band-performs-on-stage/10033627?s_phrase=rock%20concert&s_rank=193
